export enum Colors {
    Black = 30,
    Red = 31,
    Green = 32,
    Yellow = 33,
    Blue = 34,
    Magenta = 35,
    Cyan = 36,
    White = 37,
    Bright_Black = 90,
    Bright_Red = 91,
    Bright_Green = 92,
    Bright_Yellow = 93,
    Bright_Blue = 94,
    Bright_Magenta = 95,
    Bright_Cyan = 96,
    Bright_White = 97,
}

export enum Icons {
    Danger = '⚠️',
    Info = 'ℹ️',
    Success = '✅',
    Error = '❌',
    Warning = '⚠️',
    Question = '❓',
    ArrowRight = '➡️',
    ArrowLeft = '⬅️',
    ArrowUp = '⬆️',
    ArrowDown = '⬇️',
    Check = '✔️',
    Cross = '✖️',
    Star = '⭐',
    Heart = '❤️',
    Lock = '🔒',
    Unlock = '🔓',
    Bell = '🔔',
    Calendar = '📅',
    Clock = '⏰',
    File = '📄',
    Folder = '📁',
    Trash = '🗑️',
    Edit = '✏️',
    Mail = '✉️',
    Phone = '📞',
    Map = '🗺️',
    Pin = '📍',
    Chat = '💬',
    Search = '🔍',
    Settings = '⚙️',
    Sun = '☀️',
    Moon = '🌙',
}